/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTable;

/**
 *
 * @author Thiago
 */
public class NotificacoesView extends javax.swing.JFrame {

    /**
     * Creates new form NotificacoesView
     */
    public NotificacoesView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNotificacoes = new javax.swing.JTable();
        jRadioButtonVisualizar = new javax.swing.JRadioButton();
        jRadioButtonCompartilhar = new javax.swing.JRadioButton();
        jRadioButtonExcluir = new javax.swing.JRadioButton();
        buttonGroup1.add(jRadioButtonExcluir);
        buttonGroup1.add(jRadioButtonVisualizar);
        buttonGroup1.add(jRadioButtonCompartilhar);
        jRadioButtonExcluir.setActionCommand("3");
        jRadioButtonVisualizar.setActionCommand("1");
        jRadioButtonCompartilhar.setActionCommand("2");
        jLabelInformativo = new javax.swing.JLabel();
        jButtonConceder = new javax.swing.JButton();
        jButtonNegar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Notificações");

        jTableNotificacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Descrição", "Imagem", "Remetente"
            }
        ));
        jTableNotificacoes.getColumn("Descrição").setMinWidth(250);
        jTableNotificacoes.setRowHeight(50);
        jScrollPane1.setViewportView(jTableNotificacoes);

        jRadioButtonVisualizar.setSelected(true);
        jRadioButtonVisualizar.setText("(1)Visualização");

        jRadioButtonCompartilhar.setText("(2)Compartilharmento");

        jRadioButtonExcluir.setText("(3)Exclusão");

        jLabelInformativo.setText("Os niveis são acumlativos");

        jButtonConceder.setText("Conceder Acesso");

        jButtonNegar.setText("Negar Acesso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonVisualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonCompartilhar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonExcluir)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNegar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonConceder)
                        .addGap(40, 40, 40)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelInformativo))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonVisualizar)
                    .addComponent(jRadioButtonCompartilhar)
                    .addComponent(jRadioButtonExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConceder)
                    .addComponent(jButtonNegar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelInformativo))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public JButton getjButtonConceder() {
        return jButtonConceder;
    }

    public JButton getjButtonNegar() {
        return jButtonNegar;
    }

    public JRadioButton getjRadioButtonCompartilhar() {
        return jRadioButtonCompartilhar;
    }

    public JRadioButton getjRadioButtonExcluir() {
        return jRadioButtonExcluir;
    }

    public JRadioButton getjRadioButtonVisualizar() {
        return jRadioButtonVisualizar;
    }

    public JTable getjTableNotificacoes() {
       
        return jTableNotificacoes;
    }

    public JLabel getjLabelInformativo() {
        return jLabelInformativo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonConceder;
    private javax.swing.JButton jButtonNegar;
    private javax.swing.JLabel jLabelInformativo;
    private javax.swing.JRadioButton jRadioButtonCompartilhar;
    private javax.swing.JRadioButton jRadioButtonExcluir;
    private javax.swing.JRadioButton jRadioButtonVisualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNotificacoes;
    // End of variables declaration//GEN-END:variables
}
